name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Setup bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: 1.2.21

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: Extract versions
        run: |
          echo "GIT_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "CM_VERSION=$(node -p "require('./packages/codemirror-surrealql/package.json').version")" >> $GITHUB_ENV
          echo "LZ_VERSION=$(node -p "require('./packages/lezer-surrealql/package.json').version")" >> $GITHUB_ENV

      - name: Assert package versions
        run: |
          echo "CM_VERSION=$CM_VERSION"
          echo "LZ_VERSION=$LZ_VERSION"
          echo "GIT_TAG=$GIT_TAG"

          if [[ "v$CM_VERSION" != "$GIT_TAG" || "v$LZ_VERSION" != "$GIT_TAG" ]]; then
            echo "Version mismatch! Please correct package versions"
            exit 1
          else
            echo "Version check complete"
          fi

      - name: Build packages
        run: bun install && bun run build

      - name: Run tests
        run: bun run test

      - name: Publish all packages
        run: bun run deploy
